call code --install-extension christian-kohler.npm-intellisense
call code --install-extension christian-kohler.path-intellisense
call code --install-extension chrmarti.regex
call code --install-extension coderfee.open-html-in-browser
call code --install-extension dbaeumer.vscode-eslint
call code --install-extension eamodio.gitlens
call code --install-extension eg2.vscode-npm-script
call code --install-extension esbenp.prettier-vscode
call code --install-extension fknop.vscode-npm
call code --install-extension formulahendry.auto-close-tag
call code --install-extension formulahendry.auto-complete-tag
call code --install-extension formulahendry.auto-rename-tag
call code --install-extension jasonnutter.search-node-modules
call code --install-extension jpoissonnier.vscode-styled-components
call code --install-extension jtlowe.vscode-icon-theme
call code --install-extension lamartire.git-indicators
call code --install-extension ms-vscode.PowerShell
call code --install-extension PeterJausovec.vscode-docker
call code --install-extension shd101wyy.markdown-preview-enhanced
call code --install-extension spywhere.guides
call code --install-extension streetsidesoftware.code-spell-checker
call code --install-extension TwentyChung.jsx
call code --install-extension waderyan.nodejs-extension-pack
call code --install-extension xabikos.JavaScriptSnippets
